### ISSUE TITLE
Demosite scopes problem.

### ISSUE THREAD

**Issue by stager999** [GluuFederation/oxd-python#8]
Hi,
I have a problem with getting a token. Is there a problem with calling the function?:
`tokens = oxc.get_tokens_by_code(code, state)` (callback-login.cgi -> line 23). It should be:
`tokens = oxc.get_tokens_by_code(code, scopes, state)`

However there is another problem that scopes variable is not a list but a str and includes just "openid":
`https://....../cgi-bin/callback-login.cgi?code=8dd6acb2-35af-44a8-81f1-58ea3c90f662&scope=openid&state=glpn5k29ajr1a8gdadlvum5bp3&session_state=4ccd688c-bf15-47da-bf22-7a9518e4eb40.`

The OpenID server returns the redirect with all profiles as logged in OXD log. Could you please help? Thank you.

**Comment by tecoholic** [comment]
`tokens = oxc.get_tokens_by_code(code, scopes, state)` -> This function call is for the [v2.4.3](https://github.com/GluuFederation/oxd-python/blob/v2.4.3/oxdpython/client.py#L124) The function call has changed since [v2.4.4](https://github.com/GluuFederation/oxd-python/blob/v2.4.4/oxdpython/client.py#L160) to `tokens = oxc.get_tokens_by_code(code, state)`. If you are using the latest code from either master or [v3.0.1](https://github.com/GluuFederation/oxd-python/releases/tag/v3.0.1), there is no need to specify the `scopes` variable.

For the difference in what scopes, check the scopes variable specified in the default config at `/opt/oxd-server/conf/oxd-default-site-config.json` and also what you have specified at you `demosite.cfg` file. That would help you identify the difference in behaviours.

I am closing this ticket as this doesn't involve any bugs in the oxd-python code.
